### PR TITLE
Framework: Volume key cursor control

### PR DESCRIPTION
**Pull request by Klozz**
This feature is moved to framework so it also works with third
party keyboards.

Change-Id: I8e20240e7bee5351ab20bb3d701eb95a5fd3e112
Signed-off-by: klozz <klozz@TheXPerienceProject.org>

### CODE REVIEW

**Comment by NurKeinNeid** [comment]
Wew, I used with pleasure your ROM on my Moto G few years ago. Thanks for you pull request! I'll compile first and check that out later today. :)

**Comment by Klozz** [comment]
> Wew, I used with pleasure your ROM on my Moto G few years ago. Thanks for your pull request! I'll compile first and check that out later today. :)

Hey I'm glad to hear it :)
sure i'll wait
also i want to be a maintainer if possible :)

**Comment by NurKeinNeid** [comment]
Sure, as long as the device is not already occupied by someone else. Which device are we talking about?

**Comment by Klozz** [comment]
> Sure, as long as the device is not already occupied by someone else. Which device are we talking about?

Redmi note 9s/pro /pro max / poco m2 pro is a unified device "Miatoll"

**Comment by NurKeinNeid** [comment]
> > Sure, as long as the device is not already occupied by someone else. Which device are we talking about?
> 
> Redmi note 9s/pro /pro max / poco m2 pro is a unified device "Miatoll"

Oh, this device is very popular it seems. I get a lot of requests for maintaining. The problem is we already have two maintainers, but they are very busy with real life right now. That makes this situation difficult for me. I would like to be loyal to my maintainers and give them time but I am starting to feel pressured to act.

It is time to find a solution. I will discuss this internally and let you know.

**Comment by Klozz** [comment]
> > > Sure, as long as the device is not already occupied by someone else. Which device are we talking about?
> > 
> > 
> > Redmi note 9s/pro /pro max / poco m2 pro is a unified device "Miatoll"
> 
> Oh, this device is very popular it seems. I get a lot of requests for maintaining. The problem is we already have two maintainers, but they are very busy with real life right now. That makes this situation difficult for me. I would like to be loyal to my maintainers and give them time but I am starting to feel pressured to act.
> 
> It is time to find a solution. I will discuss this internally and let you know.

No problem :)

**Pull request merged**
